indicator-radius=110
indicator-thickness=18
inside-color=1d2021d0
inside-clear-color=3c3836d0
ring-color=98971a
ring-clear-color=b8bb26
ring-ver-color=83a598
ring-wrong-color=cc241d
key-hl-color=b8bb26
bs-hl-color=83a598
text-color=ebdbb2
line-color=00000000
line-uses-ring
