[ids]

*

[main]

# Number row
- = [
= = ]

# Top row
q = b
w = l
e = d
r = w
t = z
y = '
u = f
i = o
o = u
p = j
[ = ;
] = =

# Home row
capslock = backspace
a = n
s = r
d = t
f = s
g = g
h = y
j = h
k = a
l = e
; = i
' = ,

# Bottom row (Angle Mod)
z = x
x = m
c = c
v = v
b = q
n = p
m = k
, = .
. = -
/ = /

[shift]

# Graphite custom shifted punctuation (Kanata forks)
# Shift + y (apostrophe) -> _ (Underscore)
y = S-minus

# Shift + ' (comma) -> ? (Question mark)
' = S-slash

# Shift + . (minus) -> " (Double quote)
. = S-apostrophe

# Shift + / (slash) -> < (Less than)
/ = S-comma
